Feature/completion status
khijun/CampusFlow pull request #47
Opened 2024-12-24 08:28 UTC by iku701

이수상태 테이블   엔티티,enum 추가작성완료

2024-12-25 06:21 UTC, khijun requested changes

2024-12-25 06:21 UTC, khijun commented on src/test/java/edu/du/campusflow/hijunTest.java
> -            commonCodeService.insertCodeFromEnum(DeptStatus.class);
다른 사람이 수정중인 파일 같이 수정하면 병합충돌 나니까 웬만하면 터치 ㄴㄴ

2024-12-25 06:21 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/CompletionStatus.java
> +}
저희 이수 상태 컬럼으로 관리한다 하지 않았나요? 
테이블로 따로 이수상태 관리해도 수강신청에 강의랑 학생 외래키 관계 맺어있으니까 참조해서 갖고오면 될듯

2024-12-26 01:18 UTC, HyukJin98 commented on src/test/java/edu/du/campusflow/hijunTest.java
> -            commonCodeService.insertCodeFromEnum(DeptStatus.class);
ㅇㅋ

2024-12-26 07:03 UTC, closed without merging

2024-12-26 07:03 UTC, khijun commented
새 브랜치로 변경