Feature/notice
khijun/CampusFlow pull request #48
Opened 2024-12-24 08:32 UTC by sin-seong

리 트..
박습니다..

2024-12-25 06:53 UTC, khijun requested changes

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/AcademicCalendar.java
> +    @JoinColumn(name = "staff_id", nullable = false) // 외래 키 설정
nullable false 관리하기 힘드니까 nullable 다 빼주세요

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/AcademicCalendar.java
> +    private String description; // 추가 필드
주석이 좀 이상한 것 같아요

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +    private List<Inquiry> responses; // 이 문의에 대한 답변 목록
답변과 답변목록 둘 다 있는게 이상합니다

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Post.java
> +    }
평소에 쓰셨으면 괜찮은데 처음쓰시면 엔티티 인서트랑 업데이트할 때 필드값 주입에 유의해야할듯

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/repository/InquiryRepository.java
> +    List<Inquiry> findByResponseTo(Inquiry responseTo);
답변목록에 답변이 포함되는데 답변으로 답변목록을 찾는다는게 이상함

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/service/InquiryService.java
> +        inquiry.setStatus(InquiryStatus.PENDING); // 기본 상태 설정
enum이라 CommonCode로 안들어감

2024-12-25 06:53 UTC, khijun commented on src/main/java/edu/du/campusflow/service/InquiryService.java
> +    }
List에 null값을 반환하지 말고 빈 리스트를 반환하는게 좋아요

2024-12-25 06:53 UTC, khijun commented on src/test/java/edu/du/campusflow/hijunTest.java
> +            commonCodeService.insertCodeFromEnum(InquiryStatus.class);
테스트코드 여기에 추가하지 말고 각자 test폴더에 Test파일 만들어서 쓰세요 서로가 같은 파일 저렇게 수정하면 병합충돌 납니다

2024-12-26 01:19 UTC, HyukJin98 commented on src/main/java/edu/du/campusflow/entity/AcademicCalendar.java
> +    @JoinColumn(name = "staff_id", nullable = false) // 외래 키 설정
ㅇㅋ

2024-12-26 05:36 UTC, closed without merging