Feature/notice Hm..
khijun/CampusFlow pull request #52
Opened 2024-12-26 06:18 UTC by sin-seong

2024-12-26 07:32 UTC, khijun requested changes

2024-12-26 07:32 UTC, khijun commented on src/main/java/edu/du/campusflow/enums/InquiryStatus.java
> +   }
게터랑 컨스트럭터랑 필드 지워주세요

2024-12-26 07:32 UTC, khijun commented on src/main/java/edu/du/campusflow/service/InquiryService.java
서비스는 안볼게요 아직 로직단계를 모르니까

2024-12-26 07:32 UTC, khijun commented on src/test/java/edu/du/campusflow/InquiryFlowTest.java
이거 기능별로 테스트파일 만들기엔 너무 기니까 각자 이름으로 테스트파일 만들어서 실험하셔요

2024-12-26 07:32 UTC, khijun commented on src/test/java/edu/du/campusflow/hijunTest.java
엄.. 다른사람 테스트파일 수정 ㄴㄴ

2024-12-26 07:32 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +}
ㄱㄷ

2024-12-26 07:33 UTC, khijun commented
마지막 커밋하고 파일 푸쉬하기 전에 develop이랑 병합도 해주세요

2024-12-26 07:35 UTC, sin-seong commented on src/test/java/edu/du/campusflow/hijunTest.java
이건전에 잘못 추가한거 지운거인듯한

2024-12-26 07:38 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +}
한 문의에 한 답변으로 할거면 1대1로 하시고 아니면 1대다로 해주세요

2024-12-26 08:48 UTC, khijun requested changes

2024-12-26 08:48 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +    private Inquiry relatedInquiry;
이거 1대1이라 양방향 한 필드에서 되니까 지워버리셔요

2024-12-26 08:48 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +    private Inquiry responseTo; // 이 문의에 대한 답변
@OneToOne(mappedBy = "Inquiry")로 바꾸시고 실행해서 테이블 구조 잘 돌아가나 확인 ㄱㄱ

2024-12-27 05:20 UTC, sin-seong commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +    private Inquiry responseTo; // 이 문의에 대한 답변
저거 저걸로 바꿀려하니깐 돌아가질 않는거같은..느낌이

2024-12-27 05:44 UTC, khijun commented on src/main/java/edu/du/campusflow/entity/Inquiry.java
> +    private Inquiry responseTo; // 이 문의에 대한 답변
아 ㅇㅋㅇㅋ

2024-12-27 05:50 UTC, khijun approved these changes

2024-12-27 05:50 UTC, merged